server.port: 7002

netty:
  #  clients:
  #    - name: server
  #      host: localhost
  #      port: 6001
  #    - name: server
  #      host: localhost
  #      port: 6001
  server:
    port: 6002
    name: server2
  eureka:
    enable: true
    server:
      pool:
        coresize: 45
        keepalive:
          time: 15000000
        maxsize: 90


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: client
